// Contenu pédagogique — darija marocaine.
// Transcription latine "arabizi" : 3 = ع, 7 = ح, 9 = ق, kh = خ, gh = غ, ch = ش.

const w = (id, fr, dr, ar, emoji, tip) => ({ id, fr, dr, ar, emoji, tip });

export const UNITS = [
  {
    id: 'salam',
    title: 'Salutations',
    emoji: '👋',
    color: '#f59e0b',
    kind: 'phrase',
    kid: true,
    notes: [
      'On répond à « Salam 3likoum » par « W 3likoum salam ».',
      'Le masculin et le féminin changent : « Kif dayer ? » à un garçon, « Kif dayra ? » à une fille.',
      '« L7amdoulillah » (Dieu merci) sert de réponse passe-partout à « ça va ? ».',
    ],
    items: [
      w('sal1', 'Salut', 'Salam', 'سلام', '👋'),
      w('sal2', 'Bonjour (poli)', 'Salam 3likoum', 'السلام عليكم', '🙏', 'Réponse : W 3likoum salam'),
      w('sal3', 'Bonjour (le matin)', 'Sba7 lkhir', 'صباح الخير', '🌅'),
      w('sal4', 'Bonsoir', 'Msa lkhir', 'مسا الخير', '🌆'),
      w('sal5', 'Comment ça va ?', 'Kif dayer', 'كيف داير', '🙂', 'À une fille : Kif dayra ?'),
      w('sal6', 'Ça va ?', 'Labas', 'لاباس', '👍', 'Sert aussi de réponse : « Labas » = ça va.'),
      w('sal7', 'Ça va, Dieu merci', 'L7amdoulillah', 'الحمد لله', '😊'),
      w('sal8', 'Je vais bien', 'Bikhir', 'بخير', '😃'),
      w('sal9', 'Comment tu t’appelles ?', 'Chnou smitek', 'شنو سميتك', '🏷️'),
      w('sal10', 'Je m’appelle…', 'Smiti', 'سميتي', '🙋'),
      w('sal11', 'Enchanté(e)', 'Mtcharfin', 'متشرفين', '🤝'),
      w('sal12', 'Au revoir', 'Bslama', 'بسلامة', '🚪'),
      w('sal13', 'Bonne nuit', 'Tsbe7 3la khir', 'تصبح على خير', '🌙'),
      w('sal14', 'Quel âge as-tu ?', 'Ch7al f 3merek', 'شحال فعمرك', '🎂'),
    ],
  },
  {
    id: 'chiffres',
    title: 'Les chiffres',
    emoji: '🔢',
    color: '#6366f1',
    kind: 'word',
    kid: true,
    notes: [
      '« Jouj » (2) est propre au darija : en arabe classique on dirait « itnan ».',
      'Pour compter des objets on dit souvent « jouj d…​ » : jouj d le9hawi = deux cafés.',
    ],
    items: [
      w('num1', 'Un', 'Wa7ed', 'واحد', '1️⃣'),
      w('num2', 'Deux', 'Jouj', 'جوج', '2️⃣'),
      w('num3', 'Trois', 'Tlata', 'تلاتة', '3️⃣'),
      w('num4', 'Quatre', 'Rb3a', 'ربعة', '4️⃣'),
      w('num5', 'Cinq', 'Khamsa', 'خمسة', '5️⃣'),
      w('num6', 'Six', 'Setta', 'ستة', '6️⃣'),
      w('num7', 'Sept', 'Sb3a', 'سبعة', '7️⃣'),
      w('num8', 'Huit', 'Tmnya', 'تمنية', '8️⃣'),
      w('num9', 'Neuf', 'Ts3oud', 'تسعود', '9️⃣'),
      w('num10', 'Dix', '3achra', 'عشرة', '🔟'),
      w('num11', 'Onze', '7dach', 'حضاش', '1️⃣1️⃣'),
      w('num12', 'Douze', 'Tnach', 'طناش', '1️⃣2️⃣'),
      w('num13', 'Treize', 'Tletach', 'تلطاش', '1️⃣3️⃣'),
      w('num14', 'Quatorze', 'Rbe3tach', 'ربعطاش', '1️⃣4️⃣'),
      w('num15', 'Quinze', 'Khmestach', 'خمسطاش', '1️⃣5️⃣'),
      w('num20', 'Vingt', '3achrin', 'عشرين', '2️⃣0️⃣'),
      w('num100', 'Cent', 'Mya', 'مية', '💯'),
    ],
  },
  {
    id: 'couleurs',
    title: 'Les couleurs',
    emoji: '🎨',
    color: '#ec4899',
    kind: 'word',
    kid: true,
    notes: [
      'Au féminin, la couleur change : k7el → ka7la, 7mer → 7amra, byed → bida, zre9 → zer9a.',
      'Exemple : « tomobil 7amra » = une voiture rouge.',
    ],
    items: [
      w('col1', 'Blanc', 'Byed', 'بيض', '⚪', 'Féminin : bida'),
      w('col2', 'Noir', 'K7el', 'كحل', '⚫', 'Féminin : ka7la'),
      w('col3', 'Rouge', '7mer', 'حمر', '🔴', 'Féminin : 7amra'),
      w('col4', 'Bleu', 'Zre9', 'زرق', '🔵', 'Féminin : zer9a'),
      w('col5', 'Vert', 'Khder', 'خضر', '🟢', 'Féminin : khadra'),
      w('col6', 'Jaune', 'Sfer', 'صفر', '🟡', 'Féminin : safra'),
      w('col7', 'Marron', '9ahwi', 'قهوي', '🟤'),
      w('col8', 'Rose', 'Wardi', 'وردي', '🌸'),
      w('col9', 'Gris', 'Rmadi', 'رمادي', '🌫️'),
      w('col10', 'Orange', 'Limouni', 'ليموني', '🟠'),
    ],
  },
  {
    id: 'contraires',
    title: 'Grand ou petit ?',
    emoji: '⚖️',
    color: '#0891b2',
    kind: 'word',
    kid: true,
    notes: [
      'L’adjectif se met après le nom : « dar kbira » = une grande maison.',
      'Au féminin on ajoute -a : kbir → kbira, sghir → sghira, skhoun → skhouna.',
    ],
    items: [
      w('opp1', 'Grand', 'Kbir', 'كبير', '🐘', 'Féminin : kbira'),
      w('opp2', 'Petit', 'Sghir', 'صغير', '🐜', 'Féminin : sghira'),
      w('opp3', 'Chaud', 'Skhoun', 'سخون', '🔥'),
      w('opp4', 'Froid', 'Bared', 'بارد', '❄️'),
      w('opp5', 'Propre', 'N9i', 'نقي', '✨'),
      w('opp6', 'Sale', 'Mwessekh', 'موسخ', '🧹'),
      w('opp7', 'Neuf', 'Jdid', 'جديد', '🆕'),
      w('opp8', 'Vieux', '9dim', 'قديم', '🕰️'),
      w('opp9', 'Facile', 'Sahel', 'ساهل', '👍'),
      w('opp10', 'Difficile', 'S3ib', 'صعيب', '😣'),
      w('opp11', 'Triste', '7zin', 'حزين', '😢'),
      w('opp12', 'Gentil', 'Drif', 'ظريف', '🥰'),
      w('opp13', 'Plein', '3amer', 'عامر', '🥛'),
      w('opp14', 'Vide', 'Khawi', 'خاوي', '🫙'),
      w('opp15', 'Lourd', 'T9il', 'ثقيل', '🏋️'),
      w('opp16', 'Léger', 'Khfif', 'خفيف', '🪶'),
      w('opp17', 'Vite', 'Bzerba', 'بزربة', '🏃'),
    ],
  },
  {
    id: 'famille',
    title: 'La famille',
    emoji: '👨‍👩‍👧',
    color: '#10b981',
    kind: 'word',
    kid: true,
    notes: [
      '« Khoya » veut dire « mon frère » : le -a final, c’est déjà « mon ».',
      '« 3ammi » = oncle du côté du père, « khali » = oncle du côté de la mère.',
    ],
    items: [
      w('fam1', 'Papa', 'Baba', 'بابا', '👨'),
      w('fam2', 'Maman', 'Mama', 'ماما', '👩', 'Aussi : yemma'),
      w('fam3', 'Mon frère', 'Khoya', 'خويا', '👦'),
      w('fam4', 'Ma sœur', 'Khti', 'ختي', '👧'),
      w('fam5', 'Grand-père', 'Jeddi', 'جدي', '👴'),
      w('fam6', 'Grand-mère', 'Jedda', 'جدة', '👵'),
      w('fam7', 'Oncle', '3ammi', 'عمي', '🧔'),
      w('fam8', 'Tante', 'Khalti', 'خالتي', '👩‍🦰'),
      w('fam9', 'Un garçon', 'Weld', 'ولد', '🧒'),
      w('fam10', 'Une fille', 'Bent', 'بنت', '💁‍♀️'),
      w('fam11', 'Un bébé', 'Bebi', 'بيبي', '👶'),
      w('fam12', 'La famille', 'L3ayla', 'العايلة', '👨‍👩‍👧‍👦'),
      w('fam13', 'Les parents', 'Baba w mama', 'بابا و ماما', '👪'),
      w('fam14', 'Mon cousin', 'Weld 3ammi', 'ولد عمي', '🧑'),
      w('fam15', 'Ma cousine', 'Bent 3ammi', 'بنت عمي', '👩‍🦱'),
    ],
  },
  {
    id: 'animaux',
    title: 'Les animaux',
    emoji: '🐱',
    color: '#f97316',
    kind: 'word',
    kid: true,
    notes: ['Le pluriel est souvent irrégulier : kelb → klab (chiens), 7out → 7outa.'],
    items: [
      w('ani1', 'Un chat', 'Mech', 'مش', '🐱', 'On entend aussi « 9ett »'),
      w('ani2', 'Un chien', 'Kelb', 'كلب', '🐶'),
      w('ani3', 'Un âne', '7mar', 'حمار', '🫏'),
      w('ani4', 'Un cheval', '3awd', 'عود', '🐴'),
      w('ani5', 'Une vache', 'Begra', 'بكرة', '🐮'),
      w('ani6', 'Un mouton', '7awli', 'حولي', '🐑'),
      w('ani7', 'Une poule', 'Djaja', 'دجاجة', '🐔'),
      w('ani8', 'Un oiseau', '3sfour', 'عصفور', '🐦'),
      w('ani9', 'Un poisson', '7outa', 'حوتة', '🐟'),
      w('ani10', 'Une souris', 'Far', 'فار', '🐭'),
      w('ani11', 'Un lion', 'Sbe3', 'سبع', '🦁'),
      w('ani12', 'Un chameau', 'Jmel', 'جمل', '🐪'),
      w('ani13', 'Une abeille', 'Na7la', 'نحلة', '🐝'),
      w('ani14', 'Une tortue', 'Fekroun', 'فكرون', '🐢'),
      w('ani15', 'Un papillon', 'Fertetto', 'فرططو', '🦋'),
      w('ani16', 'Une grenouille', 'Jrana', 'جرانة', '🐸'),
      w('ani17', 'Une fourmi', 'Nemla', 'نملة', '🐜'),
      w('ani18', 'Un canard', 'Bett', 'بط', '🦆'),
      w('ani19', 'Un éléphant', 'Fil', 'فيل', '🐘'),
      w('ani20', 'Un singe', '9erd', 'قرد', '🐒'),
      w('ani21', 'Un serpent', '7ench', 'حنش', '🐍'),
    ],
  },
  {
    id: 'manger',
    title: 'Manger & boire',
    emoji: '🍞',
    color: '#ef4444',
    kind: 'word',
    kid: true,
    notes: [
      'Pour demander : « Bghit … 3afak » = je voudrais … s’il te plaît.',
      '« Bnin ! » (délicieux) est le compliment à faire à table.',
    ],
    items: [
      w('eat1', 'Du pain', 'Khobz', 'خبز', '🍞'),
      w('eat2', 'De l’eau', 'Lma', 'الما', '💧'),
      w('eat3', 'Du lait', '7lib', 'حليب', '🥛'),
      w('eat4', 'Du thé', 'Atay', 'أتاي', '🍵'),
      w('eat5', 'Du café', '9ahwa', 'قهوة', '☕'),
      w('eat6', 'Une pomme', 'Teffa7a', 'تفاحة', '🍎'),
      w('eat7', 'Une orange', 'Letchina', 'لتشينة', '🍊'),
      w('eat8', 'Une banane', 'Banana', 'بنانة', '🍌'),
      w('eat9', 'Du raisin', '3ineb', 'عنب', '🍇'),
      w('eat10', 'De la viande', 'L7em', 'لحم', '🥩'),
      w('eat11', 'Du poulet', 'Djaj', 'دجاج', '🍗'),
      w('eat12', 'Un œuf', 'Bida', 'بيضة', '🥚'),
      w('eat13', 'Du fromage', 'Jben', 'جبن', '🧀'),
      w('eat14', 'Du sucre', 'Sokkar', 'سكر', '🍬'),
      w('eat15', 'Du sel', 'Mel7', 'ملح', '🧂'),
      w('eat16', 'Le couscous', 'Kseksou', 'كسكس', '🍲'),
      w('eat17', 'Le tajine', 'Tajin', 'طاجين', '🍛'),
      w('eat18', 'Un gâteau', '7elwa', 'حلوة', '🍰'),
      w('eat19', 'Une pomme de terre', 'Batata', 'بطاطا', '🥔'),
      w('eat20', 'Une tomate', 'Matecha', 'مطيشة', '🍅'),
      w('eat21', 'Une carotte', 'Khizzou', 'خيزو', '🥕'),
      w('eat22', 'Du miel', '3sel', 'عسل', '🍯'),
      w('eat23', 'Des olives', 'Zitoun', 'زيتون', '🫒'),
      w('eat24', 'Du chocolat', 'Chokola', 'شوكولا', '🍫'),
      w('eat25', 'Du jus', '3asir', 'عصير', '🧃'),
      w('eat26', 'Une crêpe marocaine', 'Msemen', 'مسمن', '🥞'),
      w('eat27', 'La harira (soupe)', '7rira', 'حريرة', '🍜'),
    ],
  },
  {
    id: 'corps',
    title: 'Le corps',
    emoji: '🧍',
    color: '#8b5cf6',
    kind: 'word',
    kid: true,
    notes: ['Pour dire « j’ai mal » : « kayderni … » (kayderni ras = j’ai mal à la tête).'],
    items: [
      w('cor1', 'La tête', 'Ras', 'راس', '🗣️'),
      w('cor2', 'Les cheveux', 'Ch3ar', 'شعر', '💇'),
      w('cor3', 'L’œil', '3in', 'عين', '👁️'),
      w('cor4', 'L’oreille', 'Wden', 'ودن', '👂'),
      w('cor5', 'Le nez', 'Nif', 'نيف', '👃'),
      w('cor6', 'La bouche', 'Fomm', 'فم', '👄'),
      w('cor7', 'Les dents', 'Snan', 'سنان', '🦷'),
      w('cor8', 'La main', 'Yedd', 'يد', '✋'),
      w('cor9', 'La jambe', 'Rjel', 'رجل', '🦵'),
      w('cor10', 'Le ventre', 'Kerch', 'كرش', '🫄'),
      w('cor11', 'Le cœur', '9elb', 'قلب', '❤️'),
      w('cor12', 'Le dos', 'Dher', 'ظهر', '🧍'),
      w('cor13', 'Un doigt', 'Sba3', 'صبع', '👆', 'Très proche de « sbe3 » (le lion) : ici le s est plus épais.'),
      w('cor14', 'La langue', 'Lsan', 'لسان', '👅'),
      w('cor15', 'L’épaule', 'Ktef', 'كتف', '💪'),
    ],
  },
  {
    id: 'maison',
    title: 'La maison',
    emoji: '🏠',
    color: '#0ea5e9',
    kind: 'word',
    kid: true,
    notes: ['« F dar » = à la maison. « L dar » = vers la maison.'],
    items: [
      w('mai1', 'La maison', 'Dar', 'دار', '🏠'),
      w('mai2', 'La chambre', 'Bit', 'بيت', '🛌'),
      w('mai3', 'La cuisine', 'Kouzina', 'كوزينة', '🍳'),
      w('mai4', 'La salle de bain', '7mam', 'حمام', '🚿'),
      w('mai5', 'La porte', 'Bab', 'باب', '🚪'),
      w('mai6', 'La fenêtre', 'Cherjem', 'شرجم', '🪟'),
      w('mai7', 'La table', 'Tabla', 'طبلة', '🍽️'),
      w('mai8', 'La chaise', 'Korsi', 'كرسي', '🪑'),
      w('mai9', 'Le lit', 'Frach', 'فراش', '🛏️'),
      w('mai10', 'La télévision', 'Telfaza', 'تلفزة', '📺'),
      w('mai11', 'La lumière', 'Dou', 'ضو', '💡'),
      w('mai12', 'La clé', 'Mefta7', 'مفتاح', '🔑'),
      w('mai13', 'Le mur', 'L7it', 'الحيط', '🧱'),
      w('mai14', 'Le miroir', 'Mrayya', 'مرايا', '🪞'),
      w('mai15', 'Le savon', 'Sabon', 'صابون', '🧼'),
      w('mai16', 'La terrasse', 'Sto7', 'سطوح', '🏚️'),
    ],
  },
  {
    id: 'habits',
    title: 'Les habits',
    emoji: '👕',
    color: '#d946ef',
    kind: 'word',
    kid: true,
    notes: [
      'Beaucoup de mots d’habits viennent du français : chapo, tricou, robe.',
      'Pour dire « mets tes chaussures » : « lbes sebbatek ».',
    ],
    items: [
      w('hab1', 'Un pantalon', 'Serwal', 'سروال', '👖'),
      w('hab2', 'Une chemise', '9amija', 'قميجة', '👕'),
      w('hab3', 'Des chaussures', 'Sebbat', 'صباط', '👟'),
      w('hab4', 'Des babouches', 'Belgha', 'بلغة', '🥿'),
      w('hab5', 'Une djellaba', 'Jellaba', 'جلابة', '🥻'),
      w('hab6', 'Un chapeau', 'Chapo', 'شابو', '🧢'),
      w('hab7', 'Une robe', 'Rroba', 'الروبة', '👗'),
      w('hab8', 'Des chaussettes', 'Tqacher', 'تقاشر', '🧦'),
      w('hab9', 'Un manteau', 'Kabbout', 'كبوط', '🧥'),
      w('hab10', 'Un sac', 'Sak', 'ساك', '👛'),
      w('hab11', 'Des lunettes', 'Ndader', 'نضاضر', '👓'),
      w('hab12', 'Je m’habille', 'Kanlbes', 'كنلبس', '🪡'),
    ],
  },
  {
    id: 'ecole',
    title: 'École & jeux',
    emoji: '🎒',
    color: '#14b8a6',
    kind: 'word',
    kid: true,
    notes: ['« Sa7bi » = mon copain, « sa7bti » = ma copine.'],
    items: [
      w('eco1', 'L’école', 'Lmdrasa', 'المدرسة', '🏫'),
      w('eco2', 'Un livre', 'Ktab', 'كتاب', '📚'),
      w('eco3', 'Un stylo', 'Stilo', 'ستيلو', '🖊️'),
      w('eco4', 'Une feuille', 'Wer9a', 'ورقة', '📄'),
      w('eco5', 'Un jouet', 'L3ba', 'لعبة', '🧸'),
      w('eco6', 'Un ballon', 'Koura', 'كورة', '⚽'),
      w('eco7', 'Mon copain', 'Sa7bi', 'صاحبي', '🧑‍🤝‍🧑'),
      w('eco8', 'Le maître', 'Ostad', 'أستاذ', '👨‍🏫'),
      w('eco9', 'La musique', 'Mousi9a', 'موسيقى', '🎵'),
      w('eco10', 'Une image', 'Tswira', 'تصويرة', '🖼️'),
      w('eco11', 'Des ciseaux', 'M9es', 'مقص', '✂️'),
      w('eco12', 'Le calcul', 'L7issab', 'الحساب', '➕'),
      w('eco13', 'Un cartable', 'Sak dyal lmdrasa', 'ساك ديال المدرسة', '🎒'),
    ],
  },
  {
    id: 'nature',
    title: 'Dehors & la nature',
    emoji: '🌳',
    color: '#65a30d',
    kind: 'word',
    kid: true,
    notes: ['« Kayn chta » = il pleut, littéralement « il y a de la pluie ».'],
    items: [
      w('nat1', 'Le soleil', 'Chems', 'شمس', '☀️'),
      w('nat2', 'La lune', '9amar', 'قمر', '🌙'),
      w('nat3', 'Une étoile', 'Nejma', 'نجمة', '⭐'),
      w('nat4', 'La pluie', 'Chta', 'شتا', '🌧️'),
      w('nat5', 'Le vent', 'Ri7', 'ريح', '💨'),
      w('nat6', 'La mer', 'Lb7ar', 'البحر', '🌊'),
      w('nat7', 'Le sable', 'Rmel', 'رمل', '🏖️'),
      w('nat8', 'Un arbre', 'Chejra', 'شجرة', '🌳'),
      w('nat9', 'Une fleur', 'Werda', 'وردة', '🌹'),
      w('nat10', 'Le ciel', 'Sma', 'سما', '☁️'),
      w('nat11', 'La montagne', 'Jbel', 'جبل', '⛰️'),
      w('nat12', 'La neige', 'Telj', 'تلج', '❄️'),
      w('nat13', 'Le feu', 'L3afya', 'العافية', '🔥'),
      w('nat14', 'Le jardin', '3arsa', 'عرصة', '🌱'),
    ],
  },
  {
    id: 'dehors',
    title: 'On sort !',
    emoji: '🚗',
    color: '#0284c7',
    kind: 'word',
    kid: true,
    notes: ['« Nemchiw l… » = allons à… : « nemchiw l souk » = allons au marché.'],
    items: [
      w('deh1', 'Une voiture', 'Tomobil', 'طوموبيل', '🚗'),
      w('deh2', 'Un bus', 'Tobis', 'طوبيس', '🚌'),
      w('deh3', 'Un vélo', 'Bishklita', 'بيشكليتة', '🚲'),
      w('deh4', 'Un train', 'Tran', 'تران', '🚆'),
      w('deh5', 'Un avion', 'Tiyara', 'طيارة', '✈️'),
      w('deh6', 'Une barque', 'Flouka', 'فلوكة', '🛶'),
      w('deh7', 'La rue', 'Zn9a', 'زنقة', '🛣️'),
      w('deh8', 'Le marché', 'Souk', 'سوق', '🛒'),
      w('deh9', 'La plage', 'Plaj', 'بلاج', '🏝️'),
      w('deh10', 'La ville', 'Mdina', 'مدينة', '🏙️'),
      w('deh11', 'La boutique', '7anout', 'حانوت', '🏪'),
      w('deh12', 'L’hôpital', 'Sbitar', 'سبيطار', '🏥'),
      w('deh13', 'La mosquée', 'Jame3', 'جامع', '🕌'),
    ],
  },
  {
    id: 'ouca',
    title: 'Où ça ?',
    emoji: '📍',
    color: '#7c3aed',
    kind: 'word',
    kid: true,
    notes: [
      '« Fin » demande où, ces mots répondent : « Fin l ktab ? — Fou9 tabla. »',
      '« Kayn » (il y a) au masculin, « kayna » au féminin.',
    ],
    items: [
      w('pos1', 'Ici', 'Hna', 'هنا', '📍'),
      w('pos2', 'Là-bas', 'Temma', 'تما', '👉'),
      w('pos3', 'Dedans', 'Dakhel', 'داخل', '📥'),
      w('pos4', 'Dehors', 'Berra', 'برا', '📤'),
      w('pos5', 'Sur / en haut', 'Fou9', 'فوق', '⬆️'),
      w('pos6', 'Sous / en bas', 'Ta7t', 'تحت', '⬇️'),
      w('pos7', 'Devant', '9eddam', 'قدام', '⏩'),
      w('pos8', 'Derrière', 'Mour', 'مور', '⏪'),
      w('pos9', 'À côté', '7da', 'حدا', '↔️'),
      w('pos10', 'Loin', 'B3id', 'بعيد', '🔭'),
      w('pos11', 'Près', '9rib', 'قريب', '🤏'),
    ],
  },
  {
    id: 'temps',
    title: 'Le temps',
    emoji: '⏰',
    color: '#a855f7',
    kind: 'word',
    notes: ['La semaine commence le dimanche (l7ed) au Maroc.'],
    items: [
      w('tem1', 'Aujourd’hui', 'Lyoum', 'اليوم', '📅'),
      w('tem2', 'Demain', 'Ghedda', 'غدا', '⏭️'),
      w('tem3', 'Hier', 'Lbare7', 'البارح', '⏮️'),
      w('tem4', 'Maintenant', 'Daba', 'دابا', '⏱️'),
      w('tem5', 'Le matin', 'Sba7', 'صباح', '🌅'),
      w('tem6', 'L’après-midi', '3chiya', 'عشية', '🌇'),
      w('tem7', 'La nuit', 'Lil', 'ليل', '🌃'),
      w('tem8', 'Le jour', 'Nhar', 'نهار', '☀️'),
      w('tem9', 'La semaine', 'Simana', 'سيمانة', '🗓️'),
      w('tem10', 'Le mois', 'Chher', 'شهر', '📆'),
      w('tem11', 'L’année', '3am', 'عام', '🎊'),
      w('tem12', 'L’heure', 'Sa3a', 'ساعة', '🕐'),
    ],
  },
  {
    id: 'verbes',
    title: 'Les verbes utiles',
    emoji: '🏃',
    color: '#22c55e',
    kind: 'word',
    notes: [
      'Le préfixe « ka- » marque le présent : kan- (je), kat- (tu / elle), kay- (il), kan-…-u (nous).',
      'Exemple : kanakol (je mange) → katakol (tu manges) → kayakol (il mange).',
      'Pour la négation on encadre : « ma kanaklch » = je ne mange pas.',
    ],
    items: [
      w('ver1', 'Je mange', 'Kanakol', 'كناكل', '🍽️'),
      w('ver2', 'Je bois', 'Kanchreb', 'كنشرب', '🥤'),
      w('ver3', 'Je vais', 'Kanmchi', 'كنمشي', '🚶'),
      w('ver4', 'Je viens', 'Kanji', 'كنجي', '↩️'),
      w('ver5', 'Je joue', 'Kanl3eb', 'كنلعب', '⚽'),
      w('ver6', 'Je lis / j’étudie', 'Kan9ra', 'كنقرا', '📖'),
      w('ver7', 'Je dors', 'Kan3es', 'كنعس', '😴'),
      w('ver8', 'Je parle', 'Kanhder', 'كنهضر', '💬'),
      w('ver9', 'Je regarde', 'Kanchouf', 'كنشوف', '👀'),
      w('ver10', 'J’écoute', 'Kansme3', 'كنسمع', '👂'),
      w('ver11', 'J’écris', 'Kankteb', 'كنكتب', '✍️'),
      w('ver12', 'J’aime / je veux', 'Kanbghi', 'كنبغي', '❤️'),
      w('ver13', 'Je sais', 'Kan3ref', 'كنعرف', '🧠'),
      w('ver14', 'Je travaille', 'Kankhdem', 'كنخدم', '💼'),
    ],
  },
  {
    id: 'questions',
    title: 'Poser des questions',
    emoji: '❓',
    color: '#eab308',
    kind: 'phrase',
    notes: [
      '« Wach » se met devant une phrase pour en faire une question fermée : « Wach bghiti atay ? »',
      'Le mot interrogatif se place en tête de phrase, comme en français.',
    ],
    items: [
      w('que1', 'Quoi ?', 'Chnou', 'شنو', '❓'),
      w('que2', 'Où ?', 'Fin', 'فين', '📍'),
      w('que3', 'Combien ?', 'Ch7al', 'شحال', '🔢'),
      w('que4', 'Quand ?', 'Imta', 'إمتى', '⏰'),
      w('que5', 'Pourquoi ?', '3lach', 'علاش', '🤔'),
      w('que6', 'Comment ?', 'Kifach', 'كيفاش', '🛠️'),
      w('que7', 'Qui ?', 'Chkoun', 'شكون', '🧑'),
      w('que8', 'Est-ce que… ?', 'Wach', 'واش', '❔'),
      w('que9', 'Qu’est-ce que c’est ?', 'Chnou hada', 'شنو هادا', '🔍'),
      w('que10', 'Où sont les toilettes ?', 'Fin kayn l7mam', 'فين كاين الحمام', '🚻'),
      w('que11', 'Combien ça coûte ?', 'Ch7al hada', 'شحال هادا', '💰'),
      w('que12', 'Tu parles français ?', 'Wach kathder fransawiya', 'واش كتهضر فرنساوية', '🇫🇷'),
    ],
  },
  {
    id: 'magiques',
    title: 'Les mots magiques',
    emoji: '✨',
    color: '#f43f5e',
    kind: 'phrase',
    kid: true,
    notes: ['« Llah y3tik sse7a » (que Dieu te donne la santé) sert à remercier quelqu’un qui travaille.'],
    items: [
      w('mag1', 'S’il te plaît', '3afak', 'عافاك', '🙏'),
      w('mag2', 'Merci', 'Choukran', 'شكرا', '💐'),
      w('mag3', 'Pardon / excuse-moi', 'Sme7 liya', 'سمح ليا', '😔'),
      w('mag4', 'D’accord', 'Wakha', 'واخا', '👌'),
      w('mag5', 'Oui', 'Iyeh', 'إيه', '✅'),
      w('mag6', 'Non', 'Lla', 'لا', '❌'),
      w('mag7', 'Je n’ai pas compris', 'Ma fhemtch', 'ما فهمتش', '😕'),
      w('mag8', 'Répète, s’il te plaît', '3awed 3afak', 'عاود عافاك', '🔁'),
      w('mag9', 'Doucement', 'Bchwiya', 'بشوية', '🐢'),
      w('mag10', 'Allez ! / On y va !', 'Yallah', 'يالله', '🏃'),
      w('mag11', 'Bien / super', 'Mzyan', 'مزيان', '👏'),
      w('mag12', 'Délicieux', 'Bnin', 'بنين', '😋'),
      w('mag13', 'Joli', 'Zwin', 'زوين', '🌟', 'Féminin : zwina'),
      w('mag14', 'Ça suffit / c’est bon', 'Safi', 'صافي', '🛑'),
      w('mag15', 'Beaucoup', 'Bzzaf', 'بزاف', '📈'),
      w('mag16', 'Un peu', 'Chwiya', 'شوية', '📉'),
      w('mag17', 'Bon courage', 'Llah y3tik sse7a', 'الله يعطيك الصحة', '💪'),
    ],
  },
  {
    id: 'enfants',
    title: 'Ce que je dis',
    emoji: '🧸',
    color: '#fb7185',
    kind: 'phrase',
    kid: true,
    notes: [
      'On appelle quelqu’un avec « a » devant son nom : « a mama ! », « a baba ! ».',
      '« Bghit » + verbe = je veux… : bghit nel3eb (jouer), bghit nakol (manger).',
      'Une fille dit khayfa / fer7ana / salya au lieu de khayef / fer7an / sali.',
    ],
    items: [
      w('kid1', 'Je veux jouer', 'Bghit nel3eb', 'بغيت نلعب', '🧸'),
      w('kid2', 'Tu joues avec moi ?', 'Wach tel3eb m3aya', 'واش تلعب معايا', '🤝'),
      w('kid3', 'Viens, on joue !', 'Aji nel3bou', 'أجي نلعبو', '🎈'),
      w('kid4', 'C’est mon tour', 'Nouba dyali', 'نوبة ديالي', '✋'),
      w('kid5', 'C’est ton tour', 'Nouba dyalek', 'نوبة ديالك', '👉'),
      w('kid6', 'Regarde !', 'Chouf', 'شوف', '👀'),
      w('kid7', 'Attends-moi !', 'Tsennani', 'تسناني', '⏳'),
      w('kid8', 'Aide-moi, s’il te plaît', '3awenni 3afak', 'عاوني عافاك', '🙋'),
      w('kid9', 'Je peux ?', 'Wach ymken', 'واش يمكن', '🙏'),
      w('kid10', 'C’est à moi', 'Hada dyali', 'هادا ديالي', '🎒'),
      w('kid11', 'Encore !', 'Zid', 'زيد', '🔁'),
      w('kid12', 'J’ai fini', 'Sali', 'سالي', '✅'),
      w('kid13', 'J’ai mal ici', 'Kaydérni hna', 'كيضرني هنا', '🤕'),
      w('kid14', 'J’ai peur', 'Ana khayef', 'أنا خايف', '😨', 'Une fille dit : ana khayfa'),
      w('kid15', 'Je suis content', 'Ana fer7an', 'أنا فرحان', '😄', 'Une fille dit : ana fer7ana'),
      w('kid16', 'Je t’aime, maman', 'Kanbghik a mama', 'كنبغيك أ ماما', '❤️'),
      w('kid17', 'Fais-moi un bisou', '3tini boussa', 'عطيني بوسة', '😘'),
      w('kid18', 'Où est maman ?', 'Fin mama', 'فين ماما', '🔎'),
      w('kid19', 'Je ne trouve pas', 'Ma l9itch', 'ما لقيتش', '🤷'),
      w('kid20', 'Je veux rentrer à la maison', 'Bghit nemchi l dar', 'بغيت نمشي لدار', '🏠'),
      w('kid21', 'Merci, maman', 'Choukran a mama', 'شكرا أ ماما', '💐'),
      w('kid22', 'Attention !', '3ndak', 'عندك', '⚠️'),
      w('kid23', 'Assieds-toi', 'Gles', 'ݣلس', '🪑'),
      w('kid24', 'Lève-toi', 'Noud', 'نوض', '🧍'),
      w('kid25', 'Lave-toi les mains', 'Ghsel yeddik', 'غسل يديك', '🧼'),
    ],
  },
  {
    id: 'fete',
    title: 'C’est la fête !',
    emoji: '🎉',
    color: '#facc15',
    kind: 'phrase',
    kid: true,
    notes: ['« Mbrouk » sert pour tout : anniversaire, réussite, nouvelle maison.'],
    items: [
      w('fet1', 'Joyeux anniversaire !', '3id milad s3id', 'عيد ميلاد سعيد', '🎂'),
      w('fet2', 'Félicitations !', 'Mbrouk', 'مبروك', '🎉'),
      w('fet3', 'Bravo !', 'Tbarkallah 3lik', 'تبارك الله عليك', '👏'),
      w('fet4', 'Un cadeau', 'Hdiya', 'هدية', '🎁'),
      w('fet5', 'Un gâteau d’anniversaire', 'Tourta', 'تورطة', '🍰'),
      w('fet6', 'Une fête', '7efla', 'حفلة', '🎊'),
      w('fet7', 'Je danse', 'Kanchte7', 'كنشطح', '💃'),
      w('fet8', 'Je chante', 'Kanghenni', 'كنغني', '🎤'),
      w('fet9', 'Je ris', 'Kandhek', 'كنضحك', '😂'),
      w('fet10', 'Bonne fête (Aïd)', '3id mabrouk', 'عيد مبارك', '🌙'),
      w('fet11', 'Bienvenue !', 'Mer7ba bik', 'مرحبا بيك', '🚪'),
    ],
  },
  {
    id: 'quotidien',
    title: 'Phrases du quotidien',
    emoji: '💬',
    color: '#3b82f6',
    kind: 'phrase',
    notes: [
      '« Bghit » = je veux / je voudrais. Suivi d’un nom ou d’un verbe : « bghit nemchi » = je veux aller.',
      'La négation encadre le verbe : ma … ch. « Ma bghitch » = je ne veux pas.',
    ],
    items: [
      w('quo1', 'Je voudrais de l’eau, s’il te plaît', 'Bghit lma 3afak', 'بغيت الما عافاك', '💧'),
      w('quo2', 'Donne-moi du pain, s’il te plaît', '3tini khobz 3afak', 'عطيني خبز عافاك', '🍞'),
      w('quo3', 'J’ai faim', 'Ana jou3an', 'أنا جوعان', '🍽️', 'Une fille dit : jou3ana'),
      w('quo4', 'J’ai soif', 'Ana 3atchan', 'أنا عطشان', '🥤', 'Une fille dit : 3atchana'),
      w('quo5', 'Je suis fatigué', 'Ana 3ayan', 'أنا عيان', '😩'),
      w('quo6', 'Je veux dormir', 'Bghit nn3es', 'بغيت نعس', '😴'),
      w('quo7', 'Je t’aime', 'Kanbghik', 'كنبغيك', '❤️'),
      w('quo8', 'Je ne veux pas', 'Ma bghitch', 'ما بغيتش', '✋'),
      w('quo9', 'D’où viens-tu ?', 'Mnin nta', 'منين نتا', '🌍', 'À une fille : mnin nti ?'),
      w('quo10', 'Je viens de France', 'Ana men Fransa', 'أنا من فرنسا', '🇫🇷'),
      w('quo11', 'On y va !', 'Nemchiw', 'نمشيو', '🚗'),
      w('quo12', 'Attends un peu', 'Tsenna chwiya', 'تسنى شوية', '⏳'),
      w('quo13', 'Viens ici', 'Aji lhna', 'أجي لهنا', '👇'),
      w('quo14', 'C’est très bon', 'Hada bnin bzzaf', 'هادا بنين بزاف', '😋'),
      w('quo15', 'Je ne sais pas', 'Ma3reftch', 'ما عرفتش', '🤷'),
    ],
  },
];

export const ALL_ITEMS = UNITS.flatMap((u) => u.items.map((it) => ({ ...it, unit: u.id })));
export const ITEM_BY_ID = Object.fromEntries(ALL_ITEMS.map((it) => [it.id, it]));
export const UNIT_BY_ID = Object.fromEntries(UNITS.map((u) => [u.id, u]));

// Ordre d'enregistrement conseillé dans le Studio voix : ce qu'un enfant a
// besoin d'entendre en vraie voix d'abord. Le reste suit dans l'ordre des unités.
export const RECORDING_PRIORITY = ['enfants', 'magiques', 'salam', 'famille', 'manger', 'fete'];

// Guide de prononciation affiché dans l'app.
export const SOUNDS = [
  { s: '3', ar: 'ع', fr: 'Un « a » qui vient du fond de la gorge, comme si on serrait la gorge.', ex: '3afak', arEx: 'عافاك' },
  { s: '7', ar: 'ح', fr: 'Un « h » soufflé très fort, comme quand on embue une vitre.', ex: '7lib', arEx: 'حليب' },
  { s: '9', ar: 'ق', fr: 'Un « k » prononcé tout au fond, vers la luette.', ex: '9ahwa', arEx: 'قهوة' },
  { s: 'kh', ar: 'خ', fr: 'La jota espagnole, le « ch » allemand de « Bach ».', ex: 'khobz', arEx: 'خبز' },
  { s: 'gh', ar: 'غ', fr: 'Le « r » grasseyé du français, en plus roulé.', ex: 'ghedda', arEx: 'غدا' },
  { s: 'ch', ar: 'ش', fr: 'Comme « chat » en français.', ex: 'chnou', arEx: 'شنو' },
  { s: 'r', ar: 'ر', fr: 'Le « r » roulé, comme en espagnol ou en italien.', ex: 'ras', arEx: 'راس' },
  { s: 'd / t', ar: 'ض / ط', fr: 'Versions « épaisses » du d et du t, la langue plaquée en arrière.', ex: 'tajin', arEx: 'طاجين' },
];

// Encouragements de la mascotte.
export const CHEERS = ['Mzyan !', 'Bravo !', 'Zwin bzzaf !', 'Safi, tu gères !', 'Waaah !', 'Top !'];
export const RETRIES = ['Presque !', 'Encore un essai', 'Écoute bien…', 'Pas grave, on continue'];
